// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelfRef.reset));
    bufp->chgBit(oldp+1,(vlSelfRef.clk));
    bufp->chgBit(oldp+2,(vlSelfRef.is_halted));
    bufp->chgIData(oldp+3,(vlSelfRef.miss_count),32);
    bufp->chgIData(oldp+4,(vlSelfRef.hit_count),32);
    bufp->chgIData(oldp+5,(vlSelfRef.print_reg[0]),32);
    bufp->chgIData(oldp+6,(vlSelfRef.print_reg[1]),32);
    bufp->chgIData(oldp+7,(vlSelfRef.print_reg[2]),32);
    bufp->chgIData(oldp+8,(vlSelfRef.print_reg[3]),32);
    bufp->chgIData(oldp+9,(vlSelfRef.print_reg[4]),32);
    bufp->chgIData(oldp+10,(vlSelfRef.print_reg[5]),32);
    bufp->chgIData(oldp+11,(vlSelfRef.print_reg[6]),32);
    bufp->chgIData(oldp+12,(vlSelfRef.print_reg[7]),32);
    bufp->chgIData(oldp+13,(vlSelfRef.print_reg[8]),32);
    bufp->chgIData(oldp+14,(vlSelfRef.print_reg[9]),32);
    bufp->chgIData(oldp+15,(vlSelfRef.print_reg[10]),32);
    bufp->chgIData(oldp+16,(vlSelfRef.print_reg[11]),32);
    bufp->chgIData(oldp+17,(vlSelfRef.print_reg[12]),32);
    bufp->chgIData(oldp+18,(vlSelfRef.print_reg[13]),32);
    bufp->chgIData(oldp+19,(vlSelfRef.print_reg[14]),32);
    bufp->chgIData(oldp+20,(vlSelfRef.print_reg[15]),32);
    bufp->chgIData(oldp+21,(vlSelfRef.print_reg[16]),32);
    bufp->chgIData(oldp+22,(vlSelfRef.print_reg[17]),32);
    bufp->chgIData(oldp+23,(vlSelfRef.print_reg[18]),32);
    bufp->chgIData(oldp+24,(vlSelfRef.print_reg[19]),32);
    bufp->chgIData(oldp+25,(vlSelfRef.print_reg[20]),32);
    bufp->chgIData(oldp+26,(vlSelfRef.print_reg[21]),32);
    bufp->chgIData(oldp+27,(vlSelfRef.print_reg[22]),32);
    bufp->chgIData(oldp+28,(vlSelfRef.print_reg[23]),32);
    bufp->chgIData(oldp+29,(vlSelfRef.print_reg[24]),32);
    bufp->chgIData(oldp+30,(vlSelfRef.print_reg[25]),32);
    bufp->chgIData(oldp+31,(vlSelfRef.print_reg[26]),32);
    bufp->chgIData(oldp+32,(vlSelfRef.print_reg[27]),32);
    bufp->chgIData(oldp+33,(vlSelfRef.print_reg[28]),32);
    bufp->chgIData(oldp+34,(vlSelfRef.print_reg[29]),32);
    bufp->chgIData(oldp+35,(vlSelfRef.print_reg[30]),32);
    bufp->chgIData(oldp+36,(vlSelfRef.print_reg[31]),32);
    bufp->chgBit(oldp+37,(vlSelfRef.top__DOT__reset));
    bufp->chgBit(oldp+38,(vlSelfRef.top__DOT__clk));
    bufp->chgBit(oldp+39,(vlSelfRef.top__DOT__is_halted));
    bufp->chgIData(oldp+40,(vlSelfRef.top__DOT__miss_count),32);
    bufp->chgIData(oldp+41,(vlSelfRef.top__DOT__hit_count),32);
    bufp->chgIData(oldp+42,(vlSelfRef.top__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+43,(vlSelfRef.top__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+44,(vlSelfRef.top__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+45,(vlSelfRef.top__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+46,(vlSelfRef.top__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+47,(vlSelfRef.top__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+48,(vlSelfRef.top__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+49,(vlSelfRef.top__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+50,(vlSelfRef.top__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+51,(vlSelfRef.top__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+52,(vlSelfRef.top__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+53,(vlSelfRef.top__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+54,(vlSelfRef.top__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+55,(vlSelfRef.top__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+56,(vlSelfRef.top__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+57,(vlSelfRef.top__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+58,(vlSelfRef.top__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+59,(vlSelfRef.top__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+60,(vlSelfRef.top__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+61,(vlSelfRef.top__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+62,(vlSelfRef.top__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+63,(vlSelfRef.top__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+64,(vlSelfRef.top__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+65,(vlSelfRef.top__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+66,(vlSelfRef.top__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+67,(vlSelfRef.top__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+68,(vlSelfRef.top__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+69,(vlSelfRef.top__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+70,(vlSelfRef.top__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+71,(vlSelfRef.top__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+72,(vlSelfRef.top__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+73,(vlSelfRef.top__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+74,(vlSelfRef.top__DOT__cpu__DOT__reset));
    bufp->chgBit(oldp+75,(vlSelfRef.top__DOT__cpu__DOT__clk));
    bufp->chgBit(oldp+76,(vlSelfRef.top__DOT__cpu__DOT__is_halted));
    bufp->chgIData(oldp+77,(vlSelfRef.top__DOT__cpu__DOT__miss_count),32);
    bufp->chgIData(oldp+78,(vlSelfRef.top__DOT__cpu__DOT__hit_count),32);
    bufp->chgIData(oldp+79,(vlSelfRef.top__DOT__cpu__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+80,(vlSelfRef.top__DOT__cpu__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+81,(vlSelfRef.top__DOT__cpu__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+82,(vlSelfRef.top__DOT__cpu__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+83,(vlSelfRef.top__DOT__cpu__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+84,(vlSelfRef.top__DOT__cpu__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+85,(vlSelfRef.top__DOT__cpu__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+86,(vlSelfRef.top__DOT__cpu__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+87,(vlSelfRef.top__DOT__cpu__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+88,(vlSelfRef.top__DOT__cpu__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+89,(vlSelfRef.top__DOT__cpu__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+90,(vlSelfRef.top__DOT__cpu__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+91,(vlSelfRef.top__DOT__cpu__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+92,(vlSelfRef.top__DOT__cpu__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+93,(vlSelfRef.top__DOT__cpu__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+94,(vlSelfRef.top__DOT__cpu__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+95,(vlSelfRef.top__DOT__cpu__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+96,(vlSelfRef.top__DOT__cpu__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+97,(vlSelfRef.top__DOT__cpu__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+98,(vlSelfRef.top__DOT__cpu__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+99,(vlSelfRef.top__DOT__cpu__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+100,(vlSelfRef.top__DOT__cpu__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+101,(vlSelfRef.top__DOT__cpu__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+102,(vlSelfRef.top__DOT__cpu__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+103,(vlSelfRef.top__DOT__cpu__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+104,(vlSelfRef.top__DOT__cpu__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+105,(vlSelfRef.top__DOT__cpu__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+106,(vlSelfRef.top__DOT__cpu__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+107,(vlSelfRef.top__DOT__cpu__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+108,(vlSelfRef.top__DOT__cpu__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+109,(vlSelfRef.top__DOT__cpu__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+110,(vlSelfRef.top__DOT__cpu__DOT__print_reg[31]),32);
    bufp->chgIData(oldp+111,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_inst),32);
    bufp->chgIData(oldp+112,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_pc),32);
    bufp->chgIData(oldp+113,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_pc_add_4),32);
    bufp->chgBit(oldp+114,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_alu_src));
    bufp->chgBit(oldp+115,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_jal));
    bufp->chgBit(oldp+116,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_jalr));
    bufp->chgBit(oldp+117,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_branch));
    bufp->chgBit(oldp+118,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_write));
    bufp->chgBit(oldp+119,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_mem_read));
    bufp->chgCData(oldp+120,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc_or_mem_to_reg),2);
    bufp->chgBit(oldp+121,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_reg_write));
    bufp->chgIData(oldp+122,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1_data),32);
    bufp->chgIData(oldp+123,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2_data),32);
    bufp->chgIData(oldp+124,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_imm),32);
    bufp->chgCData(oldp+125,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_opcode),7);
    bufp->chgCData(oldp+126,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_funct3),3);
    bufp->chgBit(oldp+127,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_funct7_5));
    bufp->chgIData(oldp+128,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs1),32);
    bufp->chgIData(oldp+129,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rs2),32);
    bufp->chgIData(oldp+130,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_rd),32);
    bufp->chgIData(oldp+131,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc),32);
    bufp->chgIData(oldp+132,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc_add_4),32);
    bufp->chgBit(oldp+133,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_halted));
    bufp->chgBit(oldp+134,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_write));
    bufp->chgBit(oldp+135,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_is_jal));
    bufp->chgBit(oldp+136,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_is_jalr));
    bufp->chgBit(oldp+137,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_is_branch));
    bufp->chgBit(oldp+138,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_write));
    bufp->chgBit(oldp+139,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_mem_read));
    bufp->chgCData(oldp+140,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_pc_or_mem_to_reg),2);
    bufp->chgBit(oldp+141,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_reg_write));
    bufp->chgIData(oldp+142,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_alu_result),32);
    bufp->chgBit(oldp+143,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_alu_bcond));
    bufp->chgIData(oldp+144,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_dmem_data),32);
    bufp->chgIData(oldp+145,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_rd),32);
    bufp->chgIData(oldp+146,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_pc_add_imm),32);
    bufp->chgIData(oldp+147,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_pc_add_4),32);
    bufp->chgBit(oldp+148,(vlSelfRef.top__DOT__cpu__DOT__EX_MEM_is_halted));
    bufp->chgCData(oldp+149,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_pc_or_mem_to_reg),2);
    bufp->chgBit(oldp+150,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_read));
    bufp->chgBit(oldp+151,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_reg_write));
    bufp->chgIData(oldp+152,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_0),32);
    bufp->chgIData(oldp+153,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1),32);
    bufp->chgIData(oldp+154,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2),32);
    bufp->chgIData(oldp+155,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_rd),32);
    bufp->chgBit(oldp+156,(vlSelfRef.top__DOT__cpu__DOT__MEM_WB_is_halted));
    bufp->chgBit(oldp+157,(vlSelfRef.top__DOT__cpu__DOT__is_stall));
    bufp->chgBit(oldp+158,(vlSelfRef.top__DOT__cpu__DOT__rs1_is_ten));
    bufp->chgBit(oldp+159,(vlSelfRef.top__DOT__cpu__DOT__branch_taken));
    bufp->chgBit(oldp+160,(vlSelfRef.top__DOT__cpu__DOT__is_jal));
    bufp->chgBit(oldp+161,(vlSelfRef.top__DOT__cpu__DOT__is_jalr));
    bufp->chgBit(oldp+162,(vlSelfRef.top__DOT__cpu__DOT__is_branch));
    bufp->chgBit(oldp+163,(vlSelfRef.top__DOT__cpu__DOT__alu_src));
    bufp->chgCData(oldp+164,(vlSelfRef.top__DOT__cpu__DOT__pc_or_mem_to_reg),2);
    bufp->chgBit(oldp+165,(vlSelfRef.top__DOT__cpu__DOT__pc_write));
    bufp->chgBit(oldp+166,(vlSelfRef.top__DOT__cpu__DOT__reg_write));
    bufp->chgBit(oldp+167,(vlSelfRef.top__DOT__cpu__DOT__mem_read));
    bufp->chgBit(oldp+168,(vlSelfRef.top__DOT__cpu__DOT__mem_write));
    bufp->chgBit(oldp+169,(vlSelfRef.top__DOT__cpu__DOT__pc_src1));
    bufp->chgBit(oldp+170,(vlSelfRef.top__DOT__cpu__DOT__pc_src2));
    bufp->chgBit(oldp+171,(vlSelfRef.top__DOT__cpu__DOT__is_ecall));
    bufp->chgBit(oldp+172,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_is_halted));
    bufp->chgBit(oldp+173,(vlSelfRef.top__DOT__cpu__DOT__alu_bcond));
    bufp->chgBit(oldp+174,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_halted));
    bufp->chgCData(oldp+175,(vlSelfRef.top__DOT__cpu__DOT__Forwarding_rs1),2);
    bufp->chgCData(oldp+176,(vlSelfRef.top__DOT__cpu__DOT__Forwarding_rs2),2);
    bufp->chgCData(oldp+177,(vlSelfRef.top__DOT__cpu__DOT__Forwarding_ecall),2);
    bufp->chgIData(oldp+178,(vlSelfRef.top__DOT__cpu__DOT__current_pc),32);
    bufp->chgIData(oldp+179,(vlSelfRef.top__DOT__cpu__DOT__current_pc_add_4),32);
    bufp->chgIData(oldp+180,(vlSelfRef.top__DOT__cpu__DOT__next_pc),32);
    bufp->chgIData(oldp+181,(vlSelfRef.top__DOT__cpu__DOT__read_data_1),32);
    bufp->chgIData(oldp+182,(vlSelfRef.top__DOT__cpu__DOT__read_data_2),32);
    bufp->chgIData(oldp+183,(vlSelfRef.top__DOT__cpu__DOT__instr),32);
    bufp->chgIData(oldp+184,(vlSelfRef.top__DOT__cpu__DOT__imm_gen_out),32);
    bufp->chgCData(oldp+185,(vlSelfRef.top__DOT__cpu__DOT__alu_op),6);
    bufp->chgIData(oldp+186,(vlSelfRef.top__DOT__cpu__DOT__mux_regwrite_result),32);
    bufp->chgIData(oldp+187,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs2_result),32);
    bufp->chgIData(oldp+188,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs1_result),32);
    bufp->chgIData(oldp+189,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_result),32);
    bufp->chgIData(oldp+190,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc2_result),32);
    bufp->chgIData(oldp+191,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_forwarding_result),32);
    bufp->chgIData(oldp+192,(vlSelfRef.top__DOT__cpu__DOT__alu_result),32);
    bufp->chgIData(oldp+193,(vlSelfRef.top__DOT__cpu__DOT__pc_imm_adder_result),32);
    bufp->chgIData(oldp+194,(vlSelfRef.top__DOT__cpu__DOT__mem_dout),32);
    bufp->chgBit(oldp+195,(vlSelfRef.top__DOT__cpu__DOT__mem_write_final));
    bufp->chgBit(oldp+196,(vlSelfRef.top__DOT__cpu__DOT__reg_write_final));
    bufp->chgIData(oldp+197,(vlSelfRef.top__DOT__cpu__DOT__mux_alusrc_result),32);
    bufp->chgIData(oldp+198,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_imm_sl1),32);
    bufp->chgBit(oldp+199,(vlSelfRef.top__DOT__cpu__DOT__is_ready));
    bufp->chgBit(oldp+200,(vlSelfRef.top__DOT__cpu__DOT__is_output_valid));
    bufp->chgBit(oldp+201,(vlSelfRef.top__DOT__cpu__DOT__is_hit));
    bufp->chgBit(oldp+202,(vlSelfRef.top__DOT__cpu__DOT__is_cache_ready));
    bufp->chgIData(oldp+203,(vlSelfRef.top__DOT__cpu__DOT__pc_correct),32);
    bufp->chgIData(oldp+204,(vlSelfRef.top__DOT__cpu__DOT__pc_predict),32);
    bufp->chgBit(oldp+205,(vlSelfRef.top__DOT__cpu__DOT__prediction_sucess));
    bufp->chgBit(oldp+206,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_flush));
    bufp->chgBit(oldp+207,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_flush));
    bufp->chgIData(oldp+208,(vlSelfRef.top__DOT__cpu__DOT__IF_ID_pc_predict),32);
    bufp->chgIData(oldp+209,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_pc_predict),32);
    bufp->chgBit(oldp+210,(vlSelfRef.top__DOT__cpu__DOT__ID_EX_is_stall));
    bufp->chgBit(oldp+211,(vlSelfRef.top__DOT__cpu__DOT__prediction_taken));
    bufp->chgCData(oldp+212,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_op),6);
    bufp->chgIData(oldp+213,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__A),32);
    bufp->chgIData(oldp+214,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__B),32);
    bufp->chgIData(oldp+215,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__C),32);
    bufp->chgBit(oldp+216,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__alu_bcond));
    bufp->chgCData(oldp+217,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__FuncCode),4);
    bufp->chgCData(oldp+218,(vlSelfRef.top__DOT__cpu__DOT__alu__DOT__btype),2);
    bufp->chgCData(oldp+219,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__opcode),7);
    bufp->chgCData(oldp+220,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct3),3);
    bufp->chgBit(oldp+221,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct7_5));
    bufp->chgCData(oldp+222,(vlSelfRef.top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op),6);
    bufp->chgBit(oldp+223,(vlSelfRef.top__DOT__cpu__DOT__and___DOT__A));
    bufp->chgBit(oldp+224,(vlSelfRef.top__DOT__cpu__DOT__and___DOT__B));
    bufp->chgBit(oldp+225,(vlSelfRef.top__DOT__cpu__DOT__and___DOT__C));
    bufp->chgBit(oldp+226,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__reset));
    bufp->chgBit(oldp+227,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__clk));
    bufp->chgIData(oldp+228,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__current_pc),32);
    bufp->chgIData(oldp+229,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__ID_EX_pc),32);
    bufp->chgIData(oldp+230,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_correct),32);
    bufp->chgBit(oldp+231,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__prediction_sucess));
    bufp->chgBit(oldp+232,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__prediction_taken));
    bufp->chgIData(oldp+233,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_predict),32);
    bufp->chgIData(oldp+234,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[0]),25);
    bufp->chgIData(oldp+235,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[1]),25);
    bufp->chgIData(oldp+236,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[2]),25);
    bufp->chgIData(oldp+237,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[3]),25);
    bufp->chgIData(oldp+238,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[4]),25);
    bufp->chgIData(oldp+239,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[5]),25);
    bufp->chgIData(oldp+240,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[6]),25);
    bufp->chgIData(oldp+241,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[7]),25);
    bufp->chgIData(oldp+242,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[8]),25);
    bufp->chgIData(oldp+243,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[9]),25);
    bufp->chgIData(oldp+244,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[10]),25);
    bufp->chgIData(oldp+245,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[11]),25);
    bufp->chgIData(oldp+246,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[12]),25);
    bufp->chgIData(oldp+247,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[13]),25);
    bufp->chgIData(oldp+248,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[14]),25);
    bufp->chgIData(oldp+249,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[15]),25);
    bufp->chgIData(oldp+250,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[16]),25);
    bufp->chgIData(oldp+251,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[17]),25);
    bufp->chgIData(oldp+252,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[18]),25);
    bufp->chgIData(oldp+253,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[19]),25);
    bufp->chgIData(oldp+254,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[20]),25);
    bufp->chgIData(oldp+255,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[21]),25);
    bufp->chgIData(oldp+256,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[22]),25);
    bufp->chgIData(oldp+257,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[23]),25);
    bufp->chgIData(oldp+258,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[24]),25);
    bufp->chgIData(oldp+259,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[25]),25);
    bufp->chgIData(oldp+260,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[26]),25);
    bufp->chgIData(oldp+261,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[27]),25);
    bufp->chgIData(oldp+262,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[28]),25);
    bufp->chgIData(oldp+263,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[29]),25);
    bufp->chgIData(oldp+264,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[30]),25);
    bufp->chgIData(oldp+265,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table[31]),25);
    bufp->chgIData(oldp+266,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[0]),32);
    bufp->chgIData(oldp+267,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[1]),32);
    bufp->chgIData(oldp+268,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[2]),32);
    bufp->chgIData(oldp+269,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[3]),32);
    bufp->chgIData(oldp+270,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[4]),32);
    bufp->chgIData(oldp+271,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[5]),32);
    bufp->chgIData(oldp+272,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[6]),32);
    bufp->chgIData(oldp+273,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[7]),32);
    bufp->chgIData(oldp+274,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[8]),32);
    bufp->chgIData(oldp+275,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[9]),32);
    bufp->chgIData(oldp+276,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[10]),32);
    bufp->chgIData(oldp+277,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[11]),32);
    bufp->chgIData(oldp+278,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[12]),32);
    bufp->chgIData(oldp+279,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[13]),32);
    bufp->chgIData(oldp+280,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[14]),32);
    bufp->chgIData(oldp+281,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[15]),32);
    bufp->chgIData(oldp+282,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[16]),32);
    bufp->chgIData(oldp+283,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[17]),32);
    bufp->chgIData(oldp+284,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[18]),32);
    bufp->chgIData(oldp+285,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[19]),32);
    bufp->chgIData(oldp+286,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[20]),32);
    bufp->chgIData(oldp+287,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[21]),32);
    bufp->chgIData(oldp+288,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[22]),32);
    bufp->chgIData(oldp+289,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[23]),32);
    bufp->chgIData(oldp+290,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[24]),32);
    bufp->chgIData(oldp+291,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[25]),32);
    bufp->chgIData(oldp+292,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[26]),32);
    bufp->chgIData(oldp+293,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[27]),32);
    bufp->chgIData(oldp+294,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[28]),32);
    bufp->chgIData(oldp+295,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[29]),32);
    bufp->chgIData(oldp+296,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[30]),32);
    bufp->chgIData(oldp+297,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb[31]),32);
    bufp->chgCData(oldp+298,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[0]),2);
    bufp->chgCData(oldp+299,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[1]),2);
    bufp->chgCData(oldp+300,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[2]),2);
    bufp->chgCData(oldp+301,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[3]),2);
    bufp->chgCData(oldp+302,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[4]),2);
    bufp->chgCData(oldp+303,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[5]),2);
    bufp->chgCData(oldp+304,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[6]),2);
    bufp->chgCData(oldp+305,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[7]),2);
    bufp->chgCData(oldp+306,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[8]),2);
    bufp->chgCData(oldp+307,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[9]),2);
    bufp->chgCData(oldp+308,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[10]),2);
    bufp->chgCData(oldp+309,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[11]),2);
    bufp->chgCData(oldp+310,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[12]),2);
    bufp->chgCData(oldp+311,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[13]),2);
    bufp->chgCData(oldp+312,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[14]),2);
    bufp->chgCData(oldp+313,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[15]),2);
    bufp->chgCData(oldp+314,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[16]),2);
    bufp->chgCData(oldp+315,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[17]),2);
    bufp->chgCData(oldp+316,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[18]),2);
    bufp->chgCData(oldp+317,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[19]),2);
    bufp->chgCData(oldp+318,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[20]),2);
    bufp->chgCData(oldp+319,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[21]),2);
    bufp->chgCData(oldp+320,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[22]),2);
    bufp->chgCData(oldp+321,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[23]),2);
    bufp->chgCData(oldp+322,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[24]),2);
    bufp->chgCData(oldp+323,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[25]),2);
    bufp->chgCData(oldp+324,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[26]),2);
    bufp->chgCData(oldp+325,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[27]),2);
    bufp->chgCData(oldp+326,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[28]),2);
    bufp->chgCData(oldp+327,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[29]),2);
    bufp->chgCData(oldp+328,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[30]),2);
    bufp->chgCData(oldp+329,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht[31]),2);
    bufp->chgCData(oldp+330,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__bhsr),5);
    bufp->chgIData(oldp+331,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__current_pc_add_4_inBranchPrediction),32);
    bufp->chgCData(oldp+332,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb_idx),5);
    bufp->chgIData(oldp+333,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag),25);
    bufp->chgCData(oldp+334,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__idx_xor_bhsr),5);
    bufp->chgIData(oldp+335,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_4_adder__DOT__A),32);
    bufp->chgIData(oldp+336,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_4_adder__DOT__B),32);
    bufp->chgIData(oldp+337,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_4_adder__DOT__C),32);
    bufp->chgIData(oldp+338,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__unnamedblk1__DOT__i),32);
    bufp->chgIData(oldp+339,(vlSelfRef.top__DOT__cpu__DOT__branch_prediction_unit__DOT__unnamedblk2__DOT__pht_entry),32);
    bufp->chgBit(oldp+340,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__reset));
    bufp->chgBit(oldp+341,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__clk));
    bufp->chgBit(oldp+342,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_input_valid));
    bufp->chgIData(oldp+343,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__addr),32);
    bufp->chgBit(oldp+344,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_read));
    bufp->chgBit(oldp+345,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_write));
    bufp->chgIData(oldp+346,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__din),32);
    bufp->chgBit(oldp+347,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_ready));
    bufp->chgBit(oldp+348,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_output_valid));
    bufp->chgIData(oldp+349,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dout),32);
    bufp->chgBit(oldp+350,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_hit));
    bufp->chgIData(oldp+351,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__miss_count),32);
    bufp->chgIData(oldp+352,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__hit_count),32);
    bufp->chgBit(oldp+353,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_data_mem_ready));
    bufp->chgBit(oldp+354,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_data_mem_output_valid));
    bufp->chgCData(oldp+355,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__g),2);
    bufp->chgCData(oldp+356,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__bo),2);
    bufp->chgCData(oldp+357,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__idx),3);
    bufp->chgIData(oldp+358,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag),25);
    bufp->chgWData(oldp+359,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_block),128);
    bufp->chgWData(oldp+363,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem_dout),128);
    bufp->chgBit(oldp+367,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_data_mem_read));
    bufp->chgBit(oldp+368,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_data_mem_write));
    bufp->chgCData(oldp+369,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__current_state),2);
    bufp->chgCData(oldp+370,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__next_state),2);
    bufp->chgIData(oldp+371,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [0U][0U]),25);
    bufp->chgIData(oldp+372,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [0U][1U]),25);
    bufp->chgIData(oldp+373,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [1U][0U]),25);
    bufp->chgIData(oldp+374,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [1U][1U]),25);
    bufp->chgIData(oldp+375,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [2U][0U]),25);
    bufp->chgIData(oldp+376,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [2U][1U]),25);
    bufp->chgIData(oldp+377,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [3U][0U]),25);
    bufp->chgIData(oldp+378,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [3U][1U]),25);
    bufp->chgIData(oldp+379,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [4U][0U]),25);
    bufp->chgIData(oldp+380,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [4U][1U]),25);
    bufp->chgIData(oldp+381,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [5U][0U]),25);
    bufp->chgIData(oldp+382,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [5U][1U]),25);
    bufp->chgIData(oldp+383,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [6U][0U]),25);
    bufp->chgIData(oldp+384,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [6U][1U]),25);
    bufp->chgIData(oldp+385,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [7U][0U]),25);
    bufp->chgIData(oldp+386,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__tag_bank
                             [7U][1U]),25);
    bufp->chgBit(oldp+387,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [0U][0U]));
    bufp->chgBit(oldp+388,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [0U][1U]));
    bufp->chgBit(oldp+389,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [1U][0U]));
    bufp->chgBit(oldp+390,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [1U][1U]));
    bufp->chgBit(oldp+391,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [2U][0U]));
    bufp->chgBit(oldp+392,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [2U][1U]));
    bufp->chgBit(oldp+393,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [3U][0U]));
    bufp->chgBit(oldp+394,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [3U][1U]));
    bufp->chgBit(oldp+395,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [4U][0U]));
    bufp->chgBit(oldp+396,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [4U][1U]));
    bufp->chgBit(oldp+397,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [5U][0U]));
    bufp->chgBit(oldp+398,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [5U][1U]));
    bufp->chgBit(oldp+399,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [6U][0U]));
    bufp->chgBit(oldp+400,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [6U][1U]));
    bufp->chgBit(oldp+401,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [7U][0U]));
    bufp->chgBit(oldp+402,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__valid
                           [7U][1U]));
    bufp->chgBit(oldp+403,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [0U][0U]));
    bufp->chgBit(oldp+404,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [0U][1U]));
    bufp->chgBit(oldp+405,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [1U][0U]));
    bufp->chgBit(oldp+406,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [1U][1U]));
    bufp->chgBit(oldp+407,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [2U][0U]));
    bufp->chgBit(oldp+408,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [2U][1U]));
    bufp->chgBit(oldp+409,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [3U][0U]));
    bufp->chgBit(oldp+410,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [3U][1U]));
    bufp->chgBit(oldp+411,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [4U][0U]));
    bufp->chgBit(oldp+412,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [4U][1U]));
    bufp->chgBit(oldp+413,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [5U][0U]));
    bufp->chgBit(oldp+414,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [5U][1U]));
    bufp->chgBit(oldp+415,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [6U][0U]));
    bufp->chgBit(oldp+416,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [6U][1U]));
    bufp->chgBit(oldp+417,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [7U][0U]));
    bufp->chgBit(oldp+418,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__dirty
                           [7U][1U]));
    bufp->chgWData(oldp+419,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [0U][0U]),128);
    bufp->chgWData(oldp+423,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [0U][1U]),128);
    bufp->chgWData(oldp+427,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [1U][0U]),128);
    bufp->chgWData(oldp+431,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [1U][1U]),128);
    bufp->chgWData(oldp+435,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [2U][0U]),128);
    bufp->chgWData(oldp+439,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [2U][1U]),128);
    bufp->chgWData(oldp+443,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [3U][0U]),128);
    bufp->chgWData(oldp+447,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [3U][1U]),128);
    bufp->chgWData(oldp+451,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [4U][0U]),128);
    bufp->chgWData(oldp+455,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [4U][1U]),128);
    bufp->chgWData(oldp+459,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [5U][0U]),128);
    bufp->chgWData(oldp+463,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [5U][1U]),128);
    bufp->chgWData(oldp+467,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [6U][0U]),128);
    bufp->chgWData(oldp+471,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [6U][1U]),128);
    bufp->chgWData(oldp+475,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [7U][0U]),128);
    bufp->chgWData(oldp+479,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_bank
                             [7U][1U]),128);
    bufp->chgBit(oldp+483,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__cache_update));
    bufp->chgWData(oldp+484,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__cache_update_data),128);
    bufp->chgBit(oldp+488,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__cache_update_dirty));
    bufp->chgBit(oldp+489,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__cache_update_valid));
    bufp->chgWData(oldp+490,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_din),128);
    bufp->chgBit(oldp+494,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__is_data_mem_input_valid));
    bufp->chgIData(oldp+495,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__mem_addr),32);
    bufp->chgBit(oldp+496,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__which_set));
    bufp->chgBit(oldp+497,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__which_set_hit));
    bufp->chgBit(oldp+498,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__which_set_evict));
    bufp->chgBit(oldp+499,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__check_hit));
    bufp->chgIData(oldp+500,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__i),32);
    bufp->chgIData(oldp+501,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__j),32);
    bufp->chgIData(oldp+502,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [0U][0U]),32);
    bufp->chgIData(oldp+503,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [0U][1U]),32);
    bufp->chgIData(oldp+504,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [1U][0U]),32);
    bufp->chgIData(oldp+505,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [1U][1U]),32);
    bufp->chgIData(oldp+506,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [2U][0U]),32);
    bufp->chgIData(oldp+507,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [2U][1U]),32);
    bufp->chgIData(oldp+508,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [3U][0U]),32);
    bufp->chgIData(oldp+509,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [3U][1U]),32);
    bufp->chgIData(oldp+510,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [4U][0U]),32);
    bufp->chgIData(oldp+511,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [4U][1U]),32);
    bufp->chgIData(oldp+512,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [5U][0U]),32);
    bufp->chgIData(oldp+513,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [5U][1U]),32);
    bufp->chgIData(oldp+514,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [6U][0U]),32);
    bufp->chgIData(oldp+515,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [6U][1U]),32);
    bufp->chgIData(oldp+516,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [7U][0U]),32);
    bufp->chgIData(oldp+517,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__LRU_bank
                             [7U][1U]),32);
    bufp->chgBit(oldp+518,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__access_valid));
    bufp->chgBit(oldp+519,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__reset));
    bufp->chgBit(oldp+520,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__clk));
    bufp->chgBit(oldp+521,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_input_valid));
    bufp->chgIData(oldp+522,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__addr),32);
    bufp->chgBit(oldp+523,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_read));
    bufp->chgBit(oldp+524,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_write));
    bufp->chgWData(oldp+525,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__din),128);
    bufp->chgBit(oldp+529,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_output_valid));
    bufp->chgWData(oldp+530,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__dout),128);
    bufp->chgBit(oldp+534,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_ready));
    bufp->chgIData(oldp+535,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__i),32);
    bufp->chgIData(oldp+536,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__delay_counter),32);
    bufp->chgBit(oldp+537,(vlSelfRef.top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__request_arrived));
    bufp->chgCData(oldp+538,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__part_of_inst),7);
    bufp->chgBit(oldp+539,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal));
    bufp->chgBit(oldp+540,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr));
    bufp->chgBit(oldp+541,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_branch));
    bufp->chgBit(oldp+542,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read));
    bufp->chgBit(oldp+543,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write));
    bufp->chgBit(oldp+544,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src));
    bufp->chgBit(oldp+545,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__write_enable));
    bufp->chgCData(oldp+546,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__pc_or_mem_to_reg),2);
    bufp->chgBit(oldp+547,(vlSelfRef.top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall));
    bufp->chgBit(oldp+548,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__is_ecall));
    bufp->chgIData(oldp+549,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs1),32);
    bufp->chgIData(oldp+550,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs2),32);
    bufp->chgIData(oldp+551,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_rd),32);
    bufp->chgIData(oldp+552,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_rd),32);
    bufp->chgBit(oldp+553,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_reg_write));
    bufp->chgBit(oldp+554,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_reg_write));
    bufp->chgBit(oldp+555,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_mem_read));
    bufp->chgCData(oldp+556,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__Forwarding_rs1),2);
    bufp->chgCData(oldp+557,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__Forwarding_rs2),2);
    bufp->chgCData(oldp+558,(vlSelfRef.top__DOT__cpu__DOT__forwarding_unit__DOT__Forwarding_ecall),2);
    bufp->chgCData(oldp+559,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__opcode),7);
    bufp->chgIData(oldp+560,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__rs1),32);
    bufp->chgIData(oldp+561,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__rs2),32);
    bufp->chgIData(oldp+562,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__ID_EX_rd),32);
    bufp->chgIData(oldp+563,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__EX_MEM_rd),32);
    bufp->chgBit(oldp+564,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__ID_EX_mem_read));
    bufp->chgBit(oldp+565,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__EX_MEM_mem_read));
    bufp->chgBit(oldp+566,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__ID_EX_reg_write));
    bufp->chgBit(oldp+567,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__pc_write));
    bufp->chgBit(oldp+568,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__IF_ID_write));
    bufp->chgBit(oldp+569,(vlSelfRef.top__DOT__cpu__DOT__hazarddectection_unit__DOT__is_stall));
    bufp->chgBit(oldp+570,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__reset));
    bufp->chgBit(oldp+571,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__clk));
    bufp->chgIData(oldp+572,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__addr),32);
    bufp->chgIData(oldp+573,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__dout),32);
    bufp->chgIData(oldp+574,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__i),32);
    bufp->chgIData(oldp+575,(vlSelfRef.top__DOT__cpu__DOT__imem__DOT__imem_addr),32);
    bufp->chgIData(oldp+576,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__part_of_inst),32);
    bufp->chgIData(oldp+577,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out),32);
    bufp->chgCData(oldp+578,(vlSelfRef.top__DOT__cpu__DOT__imm_gen__DOT__opcode),7);
    bufp->chgIData(oldp+579,(vlSelfRef.top__DOT__cpu__DOT__mux_alusrc__DOT__in_1),32);
    bufp->chgIData(oldp+580,(vlSelfRef.top__DOT__cpu__DOT__mux_alusrc__DOT__in_2),32);
    bufp->chgBit(oldp+581,(vlSelfRef.top__DOT__cpu__DOT__mux_alusrc__DOT__ctrl));
    bufp->chgIData(oldp+582,(vlSelfRef.top__DOT__cpu__DOT__mux_alusrc__DOT__out),32);
    bufp->chgIData(oldp+583,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall__DOT__in_1),32);
    bufp->chgIData(oldp+584,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall__DOT__in_2),32);
    bufp->chgBit(oldp+585,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall__DOT__ctrl));
    bufp->chgIData(oldp+586,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall__DOT__out),32);
    bufp->chgIData(oldp+587,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_1),32);
    bufp->chgIData(oldp+588,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_2),32);
    bufp->chgIData(oldp+589,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_3),32);
    bufp->chgIData(oldp+590,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_4),32);
    bufp->chgCData(oldp+591,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__ctrl),2);
    bufp->chgIData(oldp+592,(vlSelfRef.top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__out),32);
    bufp->chgIData(oldp+593,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_1),32);
    bufp->chgIData(oldp+594,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_2),32);
    bufp->chgIData(oldp+595,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_3),32);
    bufp->chgIData(oldp+596,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_4),32);
    bufp->chgCData(oldp+597,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs1__DOT__ctrl),2);
    bufp->chgIData(oldp+598,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs1__DOT__out),32);
    bufp->chgIData(oldp+599,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_1),32);
    bufp->chgIData(oldp+600,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_2),32);
    bufp->chgIData(oldp+601,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_3),32);
    bufp->chgIData(oldp+602,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_4),32);
    bufp->chgCData(oldp+603,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs2__DOT__ctrl),2);
    bufp->chgIData(oldp+604,(vlSelfRef.top__DOT__cpu__DOT__mux_forwardrs2__DOT__out),32);
    bufp->chgBit(oldp+605,(vlSelfRef.top__DOT__cpu__DOT__mux_halt1__DOT__in_1));
    bufp->chgBit(oldp+606,(vlSelfRef.top__DOT__cpu__DOT__mux_halt1__DOT__in_2));
    bufp->chgBit(oldp+607,(vlSelfRef.top__DOT__cpu__DOT__mux_halt1__DOT__ctrl));
    bufp->chgBit(oldp+608,(vlSelfRef.top__DOT__cpu__DOT__mux_halt1__DOT__out));
    bufp->chgBit(oldp+609,(vlSelfRef.top__DOT__cpu__DOT__mux_halt2__DOT__in_1));
    bufp->chgBit(oldp+610,(vlSelfRef.top__DOT__cpu__DOT__mux_halt2__DOT__in_2));
    bufp->chgBit(oldp+611,(vlSelfRef.top__DOT__cpu__DOT__mux_halt2__DOT__ctrl));
    bufp->chgBit(oldp+612,(vlSelfRef.top__DOT__cpu__DOT__mux_halt2__DOT__out));
    bufp->chgIData(oldp+613,(vlSelfRef.top__DOT__cpu__DOT__mux_pc__DOT__in_1),32);
    bufp->chgIData(oldp+614,(vlSelfRef.top__DOT__cpu__DOT__mux_pc__DOT__in_2),32);
    bufp->chgBit(oldp+615,(vlSelfRef.top__DOT__cpu__DOT__mux_pc__DOT__ctrl));
    bufp->chgIData(oldp+616,(vlSelfRef.top__DOT__cpu__DOT__mux_pc__DOT__out),32);
    bufp->chgIData(oldp+617,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc1__DOT__in_1),32);
    bufp->chgIData(oldp+618,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc1__DOT__in_2),32);
    bufp->chgBit(oldp+619,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc1__DOT__ctrl));
    bufp->chgIData(oldp+620,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc1__DOT__out),32);
    bufp->chgIData(oldp+621,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc2__DOT__in_1),32);
    bufp->chgIData(oldp+622,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc2__DOT__in_2),32);
    bufp->chgBit(oldp+623,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc2__DOT__ctrl));
    bufp->chgIData(oldp+624,(vlSelfRef.top__DOT__cpu__DOT__mux_pcsrc2__DOT__out),32);
    bufp->chgIData(oldp+625,(vlSelfRef.top__DOT__cpu__DOT__mux_regwrite__DOT__in_1),32);
    bufp->chgIData(oldp+626,(vlSelfRef.top__DOT__cpu__DOT__mux_regwrite__DOT__in_2),32);
    bufp->chgIData(oldp+627,(vlSelfRef.top__DOT__cpu__DOT__mux_regwrite__DOT__in_3),32);
    bufp->chgIData(oldp+628,(vlSelfRef.top__DOT__cpu__DOT__mux_regwrite__DOT__in_4),32);
    bufp->chgCData(oldp+629,(vlSelfRef.top__DOT__cpu__DOT__mux_regwrite__DOT__ctrl),2);
    bufp->chgIData(oldp+630,(vlSelfRef.top__DOT__cpu__DOT__mux_regwrite__DOT__out),32);
    bufp->chgBit(oldp+631,(vlSelfRef.top__DOT__cpu__DOT__or___DOT__A));
    bufp->chgBit(oldp+632,(vlSelfRef.top__DOT__cpu__DOT__or___DOT__B));
    bufp->chgBit(oldp+633,(vlSelfRef.top__DOT__cpu__DOT__or___DOT__C));
    bufp->chgBit(oldp+634,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__reset));
    bufp->chgBit(oldp+635,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__clk));
    bufp->chgIData(oldp+636,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__next_pc),32);
    bufp->chgBit(oldp+637,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__pc_write));
    bufp->chgIData(oldp+638,(vlSelfRef.top__DOT__cpu__DOT__pc__DOT__current_pc),32);
    bufp->chgIData(oldp+639,(vlSelfRef.top__DOT__cpu__DOT__pc_4_adder__DOT__A),32);
    bufp->chgIData(oldp+640,(vlSelfRef.top__DOT__cpu__DOT__pc_4_adder__DOT__B),32);
    bufp->chgIData(oldp+641,(vlSelfRef.top__DOT__cpu__DOT__pc_4_adder__DOT__C),32);
    bufp->chgIData(oldp+642,(vlSelfRef.top__DOT__cpu__DOT__pc_imm_adder__DOT__A),32);
    bufp->chgIData(oldp+643,(vlSelfRef.top__DOT__cpu__DOT__pc_imm_adder__DOT__B),32);
    bufp->chgIData(oldp+644,(vlSelfRef.top__DOT__cpu__DOT__pc_imm_adder__DOT__C),32);
    bufp->chgBit(oldp+645,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__reset));
    bufp->chgBit(oldp+646,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__clk));
    bufp->chgCData(oldp+647,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1),5);
    bufp->chgCData(oldp+648,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2),5);
    bufp->chgCData(oldp+649,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd),5);
    bufp->chgIData(oldp+650,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rd_din),32);
    bufp->chgBit(oldp+651,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__write_enable));
    bufp->chgIData(oldp+652,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs1_dout),32);
    bufp->chgIData(oldp+653,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rs2_dout),32);
    bufp->chgIData(oldp+654,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+655,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+656,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+657,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+658,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+659,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+660,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+661,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+662,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+663,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+664,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+665,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+666,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+667,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+668,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+669,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+670,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+671,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+672,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+673,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+674,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+675,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+676,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+677,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+678,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+679,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+680,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+681,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+682,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+683,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+684,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+685,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__print_reg[31]),32);
    bufp->chgIData(oldp+686,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__i),32);
    bufp->chgIData(oldp+687,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[0]),32);
    bufp->chgIData(oldp+688,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[1]),32);
    bufp->chgIData(oldp+689,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[2]),32);
    bufp->chgIData(oldp+690,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[3]),32);
    bufp->chgIData(oldp+691,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[4]),32);
    bufp->chgIData(oldp+692,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[5]),32);
    bufp->chgIData(oldp+693,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[6]),32);
    bufp->chgIData(oldp+694,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[7]),32);
    bufp->chgIData(oldp+695,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[8]),32);
    bufp->chgIData(oldp+696,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[9]),32);
    bufp->chgIData(oldp+697,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[10]),32);
    bufp->chgIData(oldp+698,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[11]),32);
    bufp->chgIData(oldp+699,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[12]),32);
    bufp->chgIData(oldp+700,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[13]),32);
    bufp->chgIData(oldp+701,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[14]),32);
    bufp->chgIData(oldp+702,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[15]),32);
    bufp->chgIData(oldp+703,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[16]),32);
    bufp->chgIData(oldp+704,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[17]),32);
    bufp->chgIData(oldp+705,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[18]),32);
    bufp->chgIData(oldp+706,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[19]),32);
    bufp->chgIData(oldp+707,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[20]),32);
    bufp->chgIData(oldp+708,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[21]),32);
    bufp->chgIData(oldp+709,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[22]),32);
    bufp->chgIData(oldp+710,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[23]),32);
    bufp->chgIData(oldp+711,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[24]),32);
    bufp->chgIData(oldp+712,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[25]),32);
    bufp->chgIData(oldp+713,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[26]),32);
    bufp->chgIData(oldp+714,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[27]),32);
    bufp->chgIData(oldp+715,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[28]),32);
    bufp->chgIData(oldp+716,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[29]),32);
    bufp->chgIData(oldp+717,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[30]),32);
    bufp->chgIData(oldp+718,(vlSelfRef.top__DOT__cpu__DOT__reg_file__DOT__rf[31]),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
