// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(is_halted,0,0);
        CData/*0:0*/ top__DOT__reset;
        CData/*0:0*/ top__DOT__clk;
        CData/*0:0*/ top__DOT__is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_alu_src;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_read;
        CData/*1:0*/ top__DOT__cpu__DOT__ID_EX_pc_or_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_reg_write;
        CData/*6:0*/ top__DOT__cpu__DOT__ID_EX_opcode;
        CData/*2:0*/ top__DOT__cpu__DOT__ID_EX_funct3;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_funct7_5;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__IF_ID_write;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_is_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_read;
        CData/*1:0*/ top__DOT__cpu__DOT__EX_MEM_pc_or_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_alu_bcond;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_is_halted;
        CData/*1:0*/ top__DOT__cpu__DOT__MEM_WB_pc_or_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__is_stall;
        CData/*0:0*/ top__DOT__cpu__DOT__rs1_is_ten;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__is_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__alu_src;
        CData/*1:0*/ top__DOT__cpu__DOT__pc_or_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__pc_write;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__pc_src1;
        CData/*0:0*/ top__DOT__cpu__DOT__pc_src2;
        CData/*0:0*/ top__DOT__cpu__DOT__is_ecall;
        CData/*0:0*/ top__DOT__cpu__DOT__IF_ID_is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__alu_bcond;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_halted;
        CData/*1:0*/ top__DOT__cpu__DOT__Forwarding_rs1;
        CData/*1:0*/ top__DOT__cpu__DOT__Forwarding_rs2;
        CData/*1:0*/ top__DOT__cpu__DOT__Forwarding_ecall;
        CData/*5:0*/ top__DOT__cpu__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_write_final;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_write_final;
        CData/*0:0*/ top__DOT__cpu__DOT__is_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__is_hit;
        CData/*0:0*/ top__DOT__cpu__DOT__is_cache_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__prediction_sucess;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu__DOT__IF_ID_flush;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_flush;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_stall;
        CData/*0:0*/ top__DOT__cpu__DOT__prediction_taken;
        CData/*0:0*/ top__DOT__cpu__DOT____Vcellinp__pc__pc_write;
        CData/*4:0*/ top__DOT__cpu__DOT____Vcellinp__reg_file__rs1;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__prediction_sucess;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__prediction_taken;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__bhsr;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb_idx;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__idx_xor_bhsr;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_pc__DOT__ctrl;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__pc_write;
        CData/*0:0*/ top__DOT__cpu__DOT__imem__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__imem__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__clk;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs2;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rd;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__write_enable;
        CData/*6:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__part_of_inst;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__write_enable;
        CData/*1:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__pc_or_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall;
        CData/*6:0*/ top__DOT__cpu__DOT__imm_gen__DOT__opcode;
        CData/*6:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__opcode;
        CData/*0:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__ID_EX_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__EX_MEM_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__ID_EX_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__pc_write;
        CData/*0:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__IF_ID_write;
        CData/*0:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__is_stall;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt1__DOT__in_1;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt1__DOT__in_2;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt1__DOT__ctrl;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt1__DOT__out;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt2__DOT__in_1;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt2__DOT__in_2;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt2__DOT__ctrl;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_halt2__DOT__out;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_ecall__DOT__ctrl;
        CData/*1:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__ctrl;
        CData/*0:0*/ top__DOT__cpu__DOT__and___DOT__A;
        CData/*0:0*/ top__DOT__cpu__DOT__and___DOT__B;
        CData/*0:0*/ top__DOT__cpu__DOT__and___DOT__C;
        CData/*0:0*/ top__DOT__cpu__DOT__or___DOT__A;
        CData/*0:0*/ top__DOT__cpu__DOT__or___DOT__B;
        CData/*0:0*/ top__DOT__cpu__DOT__or___DOT__C;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_pcsrc1__DOT__ctrl;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_pcsrc2__DOT__ctrl;
        CData/*6:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__opcode;
        CData/*2:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct3;
        CData/*0:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct7_5;
    };
    struct {
        CData/*5:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op;
        CData/*5:0*/ top__DOT__cpu__DOT__alu__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT__alu__DOT__alu_bcond;
        CData/*3:0*/ top__DOT__cpu__DOT__alu__DOT__FuncCode;
        CData/*1:0*/ top__DOT__cpu__DOT__alu__DOT__btype;
        CData/*0:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__is_ecall;
        CData/*0:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_mem_read;
        CData/*1:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__Forwarding_rs1;
        CData/*1:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__Forwarding_rs2;
        CData/*1:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__Forwarding_ecall;
        CData/*1:0*/ top__DOT__cpu__DOT__mux_forwardrs1__DOT__ctrl;
        CData/*1:0*/ top__DOT__cpu__DOT__mux_forwardrs2__DOT__ctrl;
        CData/*0:0*/ top__DOT__cpu__DOT__mux_alusrc__DOT__ctrl;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_hit;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_data_mem_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_data_mem_output_valid;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__g;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__bo;
        CData/*3:0*/ top__DOT__cpu__DOT__cache__DOT__idx;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_data_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_data_mem_write;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__current_state;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__next_state;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__cache_update;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__cache_update_dirty;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__cache_update_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_data_mem_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__request_arrived;
        CData/*1:0*/ top__DOT__cpu__DOT__mux_regwrite__DOT__ctrl;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_pc_add_4;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs1_data;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs2_data;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_imm;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs1;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs2;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rd;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_pc_add_4;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_alu_result;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_dmem_data;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_rd;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_pc_add_imm;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_pc_add_4;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_0;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_rd;
        IData/*31:0*/ top__DOT__cpu__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__current_pc_add_4;
        IData/*31:0*/ top__DOT__cpu__DOT__next_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__read_data_1;
        IData/*31:0*/ top__DOT__cpu__DOT__read_data_2;
        IData/*31:0*/ top__DOT__cpu__DOT__instr;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen_out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_regwrite_result;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs2_result;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs1_result;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_result;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc2_result;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding_result;
        IData/*31:0*/ top__DOT__cpu__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_imm_adder_result;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_alusrc_result;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_imm_sl1;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_correct;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_predict;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_pc_predict;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_pc_predict;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__ID_EX_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_correct;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_predict;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__current_pc_add_4_inBranchPrediction;
        IData/*24:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__unnamedblk2__DOT__pht_entry;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_4_adder__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_4_adder__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_4_adder__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pc__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pc__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pc__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__pc__DOT__next_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__pc__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__imem_addr;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_4_adder__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_4_adder__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_4_adder__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rd_din;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs1_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs2_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen__DOT__part_of_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out;
        IData/*31:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__rs1;
        IData/*31:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__rs2;
        IData/*31:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__ID_EX_rd;
        IData/*31:0*/ top__DOT__cpu__DOT__hazarddectection_unit__DOT__EX_MEM_rd;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall__DOT__in_1;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_3;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__in_4;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc1__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc1__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc1__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc2__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc2__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc2__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs1;
        IData/*31:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs2;
        IData/*31:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_rd;
        IData/*31:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_rd;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_3;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs1__DOT__in_4;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs1__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_3;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs2__DOT__in_4;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs2__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_alusrc__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_alusrc__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_alusrc__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_imm_adder__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_imm_adder__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__pc_imm_adder__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__din;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__dout;
        IData/*23:0*/ top__DOT__cpu__DOT__cache__DOT__tag;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_block;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem_dout;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__cache_update_data;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__mem_din;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__mem_addr;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__addr;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__din;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__delay_counter;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_addr;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___din;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_regwrite__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_regwrite__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_regwrite__DOT__in_3;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_regwrite__DOT__in_4;
        IData/*31:0*/ top__DOT__cpu__DOT__mux_regwrite__DOT__out;
        IData/*31:0*/ __VactIterCount;
        VL_OUT(print_reg[32],31,0);
        VlUnpacked<IData/*31:0*/, 32> top__DOT__print_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__print_reg;
        VlUnpacked<IData/*24:0*/, 32> top__DOT__cpu__DOT__branch_prediction_unit__DOT__tag_table;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__branch_prediction_unit__DOT__btb;
    };
    struct {
        VlUnpacked<CData/*1:0*/, 32> top__DOT__cpu__DOT__branch_prediction_unit__DOT__pht;
        VlUnpacked<IData/*31:0*/, 16384> top__DOT__cpu__DOT__imem__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__reg_file__DOT__print_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__reg_file__DOT__rf;
        VlUnpacked<IData/*23:0*/, 16> top__DOT__cpu__DOT__cache__DOT__tag_bank;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__cpu__DOT__cache__DOT__valid;
        VlUnpacked<CData/*0:0*/, 16> top__DOT__cpu__DOT__cache__DOT__dirty;
        VlUnpacked<VlWide<4>/*127:0*/, 16> top__DOT__cpu__DOT__cache__DOT__data_bank;
        VlUnpacked<VlWide<4>/*127:0*/, 16384> top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_prediction_unit__DOT__pc_4_adder__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_pc__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__MEM_DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__pc_4_adder__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_halt1__DOT__data_width = 1U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_halt2__DOT__data_width = 1U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_ecall_forwarding__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc1__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_pcsrc2__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs1__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_forwardrs2__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_alusrc__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__pc_imm_adder__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__LINE_SIZE = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__NUM_SETS = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__MEM_DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__DELAY = 0x00000032U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__BLOCK_SIZE = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mux_regwrite__DOT__data_width = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
